// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-northeast-2:8f7eae1a-9c8a-48a6-9740-c04c742fd66c',
    'aws_cognito_region': 'ap-northeast-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'rebay-hosting-mobilehub-1061034507',
    'aws_content_delivery_bucket_region': 'ap-northeast-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1y19jd9oj1dwe.cloudfront.net',
    'aws_mobile_analytics_app_id': '2eb1f16afb4a4a5ab6c2396450fe07ac',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a4cd9996-2a77-4a33-a016-f9e78c193c0b',
    'aws_project_name': 'reBay',
    'aws_project_region': 'ap-northeast-2',
    'aws_resource_name_prefix': 'rebay-mobilehub-1061034507',
}

export default awsmobile;
